server:
  port: ${SERVER_PORT:2333}
  address: 127.0.0.1
  http2:
    enabled: false
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "${LAVALINK_SERVER_PASSWORD}"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      nico: false
      http: ${LAVALINK_HTTP_ENABLED:false}
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 5
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    playerUpdateInterval: 2
    youtubePlaylistLoadLimit: 3
    soundcloudSearchEnabled: true
    gc-warnings: true
    timeouts:
      connectTimeoutMs: 5000
      connectionRequestTimeoutMs: 5000
      socketTimeoutMs: 10000
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
metrics:
  prometheus:
    enabled: false
logging:
  level:
    root: WARN
    lavalink: WARN
    dev.lavalink.youtube: ERROR
  request:
    enabled: false
    includeClientInfo: false
    includeHeaders: false
    includeQueryString: false
    includePayload: false
