import test from 'node:test';
import assert from 'node:assert/strict';
import { hashPassword,verifyPassword,secretEqual,safeUrl } from '../lib/security';
import { visibleStatus } from '../lib/metrics';
import { playerPatch,protocolRoute,sessionPatch } from '../lib/gateway-policy';
test('passwords are salted, verifiable and never stored plaintext',async()=>{const password='example-only-password';const first=await hashPassword(password);assert.notEqual(first,await hashPassword(password));assert.ok(await verifyPassword(password,first));assert.equal(await verifyPassword('wrong',first),false);assert.equal(first.includes(password),false);});
test('node credentials never travel over public HTTP or credential-bearing URLs',()=>{assert.throws(()=>safeUrl('http://audio.example.com'));assert.throws(()=>safeUrl('http://127.0.0.1:2333'));assert.throws(()=>safeUrl('https://user:secret@example.com'));assert.throws(()=>safeUrl('https://example.com?secret=x'));assert.equal(safeUrl('https://audio.example.com').protocol,'https:');assert.equal(safeUrl('http://127.0.0.1:2333',true).hostname,'127.0.0.1');assert.throws(()=>safeUrl('http://10.0.0.1',true));});
test('monitor credentials reject short or mismatched values',()=>{assert.equal(secretEqual('short','short'),false);assert.equal(secretEqual('x'.repeat(32),'x'.repeat(32)),true);assert.equal(secretEqual('x'.repeat(32),'y'.repeat(32)),false);});
test('stale and absent monitoring cannot become healthy',()=>{const now=Date.now();assert.equal(visibleStatus('ONLINE',new Date(now-90001),now),'UNKNOWN');assert.equal(visibleStatus('ONLINE',null,now),'UNKNOWN');assert.equal(visibleStatus('DEGRADED',new Date(now-1000),now),'DEGRADED');});
test('protocol allowlist denies admin, session enumeration and alternate methods',()=>{for(const path of ['/v4/routeplanner/status','/v4/sessions','/internal/stats','/v4/sessions/x/players/not-a-guild','/v4/sessions/x/../other'])assert.equal(protocolRoute('GET',path),null);assert.equal(protocolRoute('POST','/v4/loadtracks'),null);assert.equal(protocolRoute('DELETE','/v4/sessions/abc'),null);assert.equal(protocolRoute('PATCH','/v4/sessions/abc/players/123456789012345678')?.kind,'player');});
test('player payload bounds and session expiry cannot bypass gateway quotas',()=>{assert.equal(playerPatch.safeParse({volume:151}).success,false);assert.equal(playerPatch.safeParse({volume:-1}).success,false);assert.equal(playerPatch.safeParse({voice:{token:'x',endpoint:'localhost',sessionId:'x'}}).success,false);assert.equal(playerPatch.safeParse({filters:{volume:1000}}).success,false);assert.equal(sessionPatch.safeParse({timeout:61}).success,false);assert.equal(playerPatch.safeParse({track:{encoded:null},paused:true,volume:0}).success,true);});

import { databaseConfig } from '../lib/database-config';
test('PostgreSQL URL parameters cannot downgrade explicit verified TLS',()=>{const config=databaseConfig('postgresql://test:example@db.example.com/test?sslmode=disable&ssl=false',true);assert.deepEqual(config.ssl,{rejectUnauthorized:true});assert.equal(new URL(config.connectionString!).searchParams.has('sslmode'),false);assert.equal(new URL(config.connectionString!).searchParams.has('ssl'),false);assert.equal(databaseConfig('postgresql://localhost/test',false).ssl,false);});
