'use client';
import Link from 'next/link';
import { useEffect,useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUpRight,KeyRound,ShieldCheck,LogOut,Info,Plus,Trash2 } from 'lucide-react';
import { CopyButton,useMetrics } from './overview';
type User={id:string;email:string;role:string;access_approved:boolean;disabled?:boolean};
type Key={id:string;name:string;node_id:string;bot_id:string;revoked_at:string|null};
async function api(path:string,body?:unknown){const res=await fetch(`/api/${path}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request gagal.');return data;}
export function AuthForm({register=false}:{register?:boolean}){const router=useRouter();const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{const result=await api(register?'register':'login',{email:form.get('email'),password:form.get('password')});if(register)setMessage(result.message);else router.push('/account');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="auth-layout"><div className="auth-intro"><span className="page-eyebrow">YOUR NEXT CONNECTION STARTS HERE</span><h1>{register?'Make room for the music.':'Welcome back to your workspace.'}</h1><p>Akun dashboard untuk mengelola akses, kredensial client, dan layanan audio kamu.</p><div className="auth-detail"><ShieldCheck/><span>Dashboard & audio authentication<br/><small>Dua lapisan akses yang terpisah.</small></span></div></div><section className="panel auth-card"><div className="mini-icon"><KeyRound/></div><h2>{register?'Create an account':'Log in to Resonance'}</h2><p>{register?'Mulai dengan akun. Akses audio memerlukan persetujuan admin.':'Masukkan detail akun kamu untuk melanjutkan.'}</p><form onSubmit={submit}><label>Email<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></label><label>Password<input name="password" type="password" autoComplete={register?'new-password':'current-password'} required minLength={12} maxLength={128} placeholder="Minimal 12 karakter"/></label>{register&&<label className="checkbox-label"><input type="checkbox" required/><span>Saya menyetujui <Link href="/terms">Terms of Service</Link> dan <Link href="/aup">Acceptable Use Policy</Link>.</span></label>}{error&&<div className="form-error" role="alert">{error}</div>}{message&&<div className="form-success" role="status">{message} <Link href="/login">Login →</Link></div>}<button className="button full" disabled={busy}>{busy?'Memproses…':register?'Create account':'Log in'}<ArrowUpRight size={15}/></button></form><div className="auth-switch">{register?'Sudah punya akun?':'Belum punya akun?'} <Link href={register?'/login':'/register'}>{register?'Log in':'Create account'}</Link></div></section></div>;
}
export function Account({admin=false}:{admin?:boolean}){const[user,setUser]=useState<User|null>(null);const[keys,setKeys]=useState<Key[]>([]);const[error,setError]=useState('');const[message,setMessage]=useState('');const[secret,setSecret]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[adminData,setAdminData]=useState<{users:User[];audit:{id:number;action:string;target:string;created_at:string}[];playback:{node_id:string;checked_at:string;audible_confirmed:boolean}[]}|null>(null);const router=useRouter();const{data,reload:reloadMetrics}=useMetrics();
 async function load(){try{const me=await api('me');setUser(me.user);if(me.user){setKeys(await api('keys'));if(admin)setAdminData(await api('admin'));}setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[admin]);
 async function action(path:string,body:unknown){setBusy(true);setError('');setMessage('');try{const result=await api(path,body);if(result.token)setSecret(result.token);setMessage(result.message);await load();if(path.startsWith('admin/incidents'))await reloadMetrics();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(loading)return <div className="skeleton hero" aria-label="Memuat akun"/>;
 if(!user)return <section className="panel error-page"><KeyRound/><h1>Your workspace is waiting.</h1><p>Login untuk mengelola kredensial client dan akses audio.</p>{error&&<p role="alert">{error}</p>}<Link href="/login" className="button">Log in <ArrowUpRight size={16}/></Link></section>;
 return <div className="page-enter"><div className="page-heading"><div><span className="page-eyebrow">{admin?'OPERATIONS':'YOUR WORKSPACE'}</span><h1>{admin?'Service administration.':'Your next connection.'}</h1><p>{user.email} · {user.role}</p></div><div className="inline-actions">{user.role==='admin'&&<Link href={admin?'/account':'/admin'} className="button secondary">{admin?'Your account':'Admin dashboard'}</Link>}<button className="text-button" onClick={async()=>{try{await api('logout',{});router.push('/login');}catch(e){setError((e as Error).message);}}}><LogOut size={15}/> Log out</button></div></div>{error&&<div className="notice" role="alert">{error}</div>}{message&&<div className="notice success" role="status">{message}</div>}
 {admin?adminData?<><section className="panel table-panel"><div className="panel-heading"><h3>Accounts & access approval</h3></div><table><thead><tr><th>Account</th><th>Role</th><th>Audio access</th><th>Action</th></tr></thead><tbody>{adminData.users.map(u=><tr key={u.id}><td>{u.email}</td><td>{u.role}</td><td>{u.disabled?'Disabled':u.access_approved?'Approved':'Pending'}</td><td><div className="inline-actions">{!u.access_approved&&<button className="button small" disabled={busy} onClick={()=>void action('admin/user',{id:u.id,action:'approve'})}>Approve</button>}<button className="text-button" disabled={busy||u.id===user.id} onClick={()=>void action('admin/user',{id:u.id,action:u.disabled?'enable':'disable'})}>{u.disabled?'Enable':'Revoke access'}</button></div></td></tr>)}</tbody></table></section><section className="panel form-panel"><h3>Publish an incident</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('admin/incidents',{nodeId:f.get('nodeId'),title:f.get('title'),details:f.get('details')});}}><label>Node<select name="nodeId"><option value="render">Render Node 01</option><option value="vps">VPS Node 02</option></select></label><label>Title<input name="title" required minLength={3} maxLength={120}/></label><label>Public details<textarea name="details" required minLength={3} maxLength={2000}/></label><button className="button" disabled={busy}>Publish incident</button></form>{data?.incidents.filter(i=>!i.resolved_at).map(i=><div className="incident" key={i.id}><strong>{i.title}</strong><button className="text-button" disabled={busy} onClick={()=>void action('admin/incidents/resolve',{id:i.id})}>Mark resolved</button></div>)}</section><section className="panel table-panel"><div className="panel-heading"><h3>Audit log · latest 100 events</h3></div><table><thead><tr><th>Time</th><th>Action</th><th>Target</th></tr></thead><tbody>{adminData.audit.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString('id-ID')}</td><td>{a.action}</td><td>{a.target??'—'}</td></tr>)}</tbody></table></section><section className="panel form-panel"><h3>Recorded playback evidence</h3>{adminData.playback.length?adminData.playback.map((p,i)=><p key={i}>{p.node_id} · {p.checked_at} · {p.audible_confirmed?'Human listening recorded':'No listening confirmation'}</p>):<p>Belum ada hasil tes playback yang disimpan.</p>}</section></>:<div className="notice">Akses admin diperlukan.</div>:<>
 {!user.access_approved&&<div className="notice"><Info size={17}/>Akun terdaftar. Tunggu persetujuan admin sebelum membuat kredensial audio.</div>}
 <div className="account-grid"><section className="panel form-panel"><div className="mini-icon"><KeyRound/></div><h3>Create a client credential</h3><p>Unik per node. Gunakan sebagai password pada client Lavalink bot. Ini bukan password internal node atau API key website.</p><form onSubmit={e=>{e.preventDefault();setSecret('');const f=new FormData(e.currentTarget);void action('keys',{name:f.get('name'),nodeId:f.get('nodeId'),botId:f.get('botId')});}}><label>Credential name<input name="name" placeholder="My music bot" required maxLength={60}/></label><label>Audio node<select name="nodeId"><option value="render">Render · Node 01</option><option value="vps">VPS · Node 02</option></select></label><label>Discord bot user ID<input name="botId" required pattern="[0-9]{17,20}" placeholder="Your bot user ID"/></label><button className="button" disabled={busy||!user.access_approved}><Plus size={15}/> Create credential</button></form>{secret&&<div className="secret-box"><strong>Ditampilkan sekali. Simpan sekarang.</strong><code>{secret}</code><CopyButton value={secret}/><button className="text-button" onClick={()=>setSecret('')}>Hide</button></div>}</section><section className="panel form-panel"><ShieldCheck className="violet-text"/><h3>A clear access model.</h3><ul className="feature-list"><li>Maksimal 4 kredensial aktif per akun.</li><li>1 WebSocket dan 5 player per kredensial.</li><li>120 request per menit; 20.000 per jendela 24 jam.</li><li>Volume maksimal 150%.</li><li>Pencabutan menutup koneksi dalam 15 detik.</li><li>Gunakan HTTPS/WSS pada port publik 443.</li></ul><Link href="/bot" className="text-button">Open integration guide <ArrowUpRight size={14}/></Link></section></div><section className="panel table-panel"><div className="panel-heading"><h3>Your client credentials</h3><span className="tiny-tag">{keys.filter(k=>!k.revoked_at).length} / 4 ACTIVE</span></div><table><thead><tr><th>Name</th><th>Node</th><th>Bot user ID</th><th>Status</th><th/></tr></thead><tbody>{keys.map(k=><tr key={k.id}><td>{k.name}</td><td>{k.node_id}</td><td><code>{k.bot_id}</code></td><td>{k.revoked_at?'Revoked':'Active'}</td><td>{!k.revoked_at&&<button className="text-button danger" disabled={busy} onClick={()=>void action('keys/revoke',{id:k.id})}><Trash2 size={14}/> Revoke</button>}</td></tr>)}</tbody></table>{!keys.length&&<div className="empty-inline"><KeyRound/><p>Belum ada kredensial. Buat setelah akses disetujui.</p></div>}</section></>}
 </div>;
}
