import Link from 'next/link';
import { ArrowUpRight,BookOpen,Code2,Headphones,ShieldCheck } from 'lucide-react';
import { CopyButton } from './overview';
function Code({children}:{children:string}){return <div className="code-block"><div><span>CONNECTION EXAMPLE</span><CopyButton value={children}/></div><pre><code>{children}</code></pre></div>;}
export function Documentation({bot=false}:{bot?:boolean}){return <div className="docs-layout"><article className="docs-article"><span className="page-eyebrow">{bot?'FROM CONNECTION TO PLAYBACK':'THE RESONANCE HANDBOOK'}</span><h1>{bot?'Bring your bot to life.':'Built to be connected.'}</h1><p className="lead">{bot?'Verifikasi setiap tahap, dari track yang ditemukan sampai audio yang benar-benar terdengar di Discord.':'Semua yang kamu perlukan untuk menghubungkan bot Discord ke jaringan audio Resonance.'}</p><div className="docs-cards"><div><BookOpen/><strong>Lavalink v4</strong><span>REST + WebSocket</span></div><div><ShieldCheck/><strong>Secure by default</strong><span>HTTPS / WSS · 443</span></div><div><Headphones/><strong>Playback first</strong><span>Verify the full journey</span></div></div>
 <section id="connect"><h2>01 <span>Get connected</span></h2><p>Daftar akun dan minta persetujuan akses dari operator. Buat kredensial untuk node pilihan di <Link href="/account">dashboard pengguna</Link>. Host aktual tersedia di <Link href="/nodes">halaman node</Link>; password menggunakan kredensial client yang ditampilkan sekali.</p><Code>{`// Server-side bot configuration. Never put credentials in a browser.
const node = {
  url: process.env.LAVALINK_URL, // https://your-node.example.com
  password: process.env.LAVALINK_CLIENT_KEY,
  secure: true,
  port: 443,
};
// WebSocket headers:
// Authorization: <client credential>
// User-Id: <Discord bot user ID bound to this credential>
// Client-Name: MyBot/1.0
// Path: /v4/websocket`}</Code><div className="notice">Setiap node memiliki kredensial berbeda. Akun website dan kredensial protokol audio adalah autentikasi terpisah.</div></section>
 <section id="playback"><h2>02 <span>Run the playback journey</span></h2><p>Repo menyertakan bot contoh dan runner tes nyata. Bot memerlukan izin View Channel, Connect, dan Speak; aktifkan Message Content Intent untuk command contoh. Jalankan bot pada satu proses per token.</p><Code>{`npm ci
# Set environment variables using your secret manager:
# DISCORD_TOKEN, DISCORD_GUILD_ID, DISCORD_VOICE_CHANNEL_ID
# BOT_OWNER_ID, LAVALINK_URL, LAVALINK_CLIENT_KEY
npm run bot

# In Discord, as BOT_OWNER_ID in the configured guild:
!join
!play ytsearch:your query
!pause
!resume
!volume 50
!skip
!stop
!leave`}</Code><p>Bot hanya menerima command dari BOT_OWNER_ID dan guild yang dikonfigurasi. Join diarahkan ke voice channel yang ditentukan. Queue berada di memori bot; restart bot menghapus queue.</p><Code>{`# Run separately against Node 01 and Node 02:
# TEST_TRACK_IDENTIFIER = valid, authorized track URL
# TEST_SEARCH_IDENTIFIER = ytsearch:... or scsearch:...
# TEST_PLAYLIST_IDENTIFIER = a supported playlist URL
# TEST_EXCEPTION_IDENTIFIER = controlled fixture that fails during playback
npm run test:playback
# Confirm listening interactively only after hearing audio.
# JSON report is saved in PLAYBACK_REPORT_DIR.`}</Code><ol className="checklist"><li>HTTPS dan WebSocket berhasil; ready event diterima.</li><li>Identifier, pencarian, playlist, dan decode menghasilkan track valid.</li><li>Bot join voice; voice state diteruskan ke Lavalink.</li><li>TrackStartEvent dan posisi player bergerak.</li><li>Pause, resume, volume, skip, stop, dan TrackEndEvent diuji.</li><li>TrackExceptionEvent diuji memakai sumber rusak yang terkontrol.</li><li>Listener manusia mengonfirmasi audio terdengar. Frame terkirim saja belum cukup.</li><li>Koneksi diputus lalu reconnect; outage node diuji saat maintenance.</li></ol></section>
 <section id="api"><h2>03 <span>API reference</span></h2><p>REST dan WebSocket memakai host audio yang sama. Gateway membatasi akses sesi sesuai pemilik kredensial.</p><div className="panel table-panel"><table><thead><tr><th>Endpoint</th><th>Purpose</th></tr></thead><tbody><tr><td>GET /v4/loadtracks?identifier=…</td><td>Search / resolve / playlist</td></tr><tr><td>GET /v4/decodetrack?encodedTrack=…</td><td>Decode track</td></tr><tr><td>PATCH /v4/sessions/:id</td><td>Resume session, timeout ≤60s</td></tr><tr><td>GET /v4/sessions/:id/players</td><td>Daftar player milik sesi</td></tr><tr><td>PATCH /v4/sessions/:id/players/:guild</td><td>Play, pause, volume, stop</td></tr><tr><td>DELETE /v4/sessions/:id/players/:guild</td><td>Destroy player</td></tr><tr><td>GET /api/public · website</td><td>Statistik agregat dan insiden publik</td></tr></tbody></table></div><p>Endpoint akun menggunakan cookie HttpOnly + pemeriksaan Origin. API key website tidak diperlukan untuk statistik publik dan tidak memberi akses audio. Respons 429 berarti kuota terlampaui; patuhi Retry-After.</p></section>
 <section id="reconnect"><h2>04 <span>Reconnect with intent</span></h2><p>Bot contoh menggunakan reconnect dengan exponential backoff terbatas dan session resuming pada node yang sama. Tidak ada failover otomatis. Untuk pindah node: pilih endpoint dan kredensial node tujuan, join ulang voice, resolve ulang track, lalu buat player baru. Sesi aktif mungkin tidak bisa dipulihkan.</p></section>
 <section id="metrics"><h2>05 <span>Metrics that mean something</span></h2><p>Active Players adalah player Lavalink; Currently Playing adalah player yang memutar. Connected Clients adalah lease WebSocket aktif yang diperbarui setiap 15 detik; koneksi terputus tanpa cleanup dapat terhitung hingga 45 detik. Daily Active Clients adalah kredensial unik per node per hari UTC, termasuk reconnect tanpa menghitung ulang.</p><p>ID bot diklaim client, bukan identitas bot yang diverifikasi oleh Discord. Satu bot dapat memakai lebih dari satu kredensial. Tidak ada metrik “pengguna Discord unik”. Akun website disimpan terpisah.</p><p>Latency mengukur round trip HTTPS ke gateway dan query statistik. CPU dan RAM adalah proses JVM Lavalink. Uptime adalah persentase sampel ONLINE selama 24 jam, dengan coverage terpisah. Data lebih tua dari 90 detik menjadi UNKNOWN.</p><p>Error rate adalah request REST terautentikasi yang berakhir HTTP ≥400 atau loadType error dibagi request terautentikasi. TrackExceptionEvent dihitung terpisah. Raw identifier, token voice, dan isi track tidak disimpan dalam telemetry. Sampel, request bucket, dan client day disimpan 30 hari; audit 90 hari.</p></section>
 <section id="sources"><h2>06 <span>Supported sources & limitations</span></h2><p>Konfigurasi memuat plugin YouTube 1.18.2 dan source SoundCloud. Ketersediaan bergantung pada sumber, IP, dan hasil pengujian saat itu. Spotify tidak diaktifkan. Tidak ada janji semua platform musik didukung. Sumber HTTP umum dimatikan secara default untuk membatasi akses ke jaringan internal.</p><p>Jika source gagal, gateway mengembalikan SOURCE_LOAD_FAILED atau SOURCE_PLAYBACK_FAILED. Periksa identifier, akses sumber dari node yang sama, versi plugin, serta log yang sudah disanitasi. Jangan menganggap hasil pencarian membuktikan stream dapat diputar.</p></section>
 <section id="render"><h2>07 <span>Render playback gate</span></h2><p>Render mendukung WebSocket pada web service dan TLS di edge. Port publik 443 meneruskan kontrol HTTPS/WSS ke gateway; trafik voice UDP keluar dari proses Lavalink ke Discord melalui jalur berbeda.</p><div className="notice">Node Render belum boleh dinyatakan playback-ready sampai tes pada instance Render sebenarnya membuktikan koneksi sumber, voice handshake, UDP, dan audio terdengar. Sandbox lokal tidak membuktikan kemampuan Render.</div><p>Jika voice UDP atau streaming sumber tidak andal, pertahankan website, API, dan PostgreSQL di Render, lalu ajukan pemindahan komputasi audio Node 01 ke VPS/VM dengan UDP keluar yang teruji. Itu mengubah persyaratan lokasi Node 01 dan perlu keputusan operator.</p><p>Sumber resmi: <a href="https://render.com/docs/websocket">Render WebSockets</a>, <a href="https://render.com/docs/web-services#port-binding">Render port binding</a>, <a href="https://lavalink.dev/api/rest.html">Lavalink REST</a>, <a href="https://github.com/lavalink-devs/Lavalink/releases/tag/4.2.2">Lavalink 4.2.2</a>.</p></section>
 </article><aside className="docs-toc"><span>ON THIS PAGE</span>{[['connect','Get connected'],['playback','Playback journey'],['api','API reference'],['reconnect','Reconnect'],['metrics','Metric definitions'],['sources','Audio sources'],['render','Render readiness']].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}<div><Code2 size={22}/><h4>Ready to connect?</h4><p>Your audio starts with a client credential.</p><Link href="/account">Open workspace <ArrowUpRight size={14}/></Link></div></aside></div>;}
export function Policy({aup=false}:{aup?:boolean}){return <article className="prose-page"><span className="page-eyebrow">RESONANCE · SERVICE POLICY</span><h1>{aup?'Acceptable Use Policy':'Terms of Service'}</h1><p className="lead">Aturan operasional untuk akses publik yang terkontrol.</p>{aup?<><h2>Penggunaan yang diperbolehkan</h2><p>Gunakan layanan untuk audio bot Discord yang memiliki izin di server tujuan dan konten yang berhak kamu akses. Patuhi ketentuan Discord serta penyedia sumber audio.</p><h2>Batas penggunaan</h2><p>Setiap kredensial: satu koneksi WebSocket, lima player, 120 request per menit, dan 20.000 request per jendela 24 jam. Maksimal empat kredensial aktif per akun. Batas dapat diperbarui melalui changelog.</p><h2>Aktivitas terlarang</h2><p>Dilarang membagikan kredensial secara publik, menghindari kuota, mengakses jaringan internal, memindai host, melakukan denial of service, atau memakai layanan untuk konten tanpa izin.</p><h2>Penanganan penyalahgunaan</h2><p>Operator dapat mencabut kredensial atau menonaktifkan akun. Pencabutan menghentikan koneksi aktif dan membatalkan akses baru. Perubahan administratif dicatat dalam audit log.</p></>:<><h2>Akses & tanggung jawab</h2><p>Registrasi website tidak otomatis memberikan akses audio. Akses audio memerlukan persetujuan operator dan kredensial per node. Pemilik akun bertanggung jawab menjaga kredensial bot.</p><h2>Ketersediaan</h2><p>Tidak ada SLA yang dijanjikan. Source audio dapat berubah atau menolak streaming. Status ONLINE menunjukkan probe kontrol berhasil; status tersebut tidak menjamin playback atau akses semua platform.</p><h2>Data yang disimpan</h2><p>Layanan menyimpan email, hash password, role, ID bot yang diklaim, hash kredensial, kuota, dan telemetry agregat. Password internal node tidak dikirim ke browser. Raw IP dan voice token tidak disimpan dalam monitoring.</p><h2>Retensi & pencabutan</h2><p>Telemetry detail disimpan 30 hari dan audit log 90 hari. Sesi login kedaluwarsa setelah tujuh hari. Kredensial bisa dicabut dari workspace. Untuk penghapusan akun, hubungi operator yang memberikan akses layanan; operator harus menyediakan kanal kontak sebelum membuka registrasi publik.</p><h2>Keamanan transport</h2><p>Gunakan HTTPS/WSS. Port 80 di VPS hanya untuk ACME/redirect, tanpa request yang membawa kredensial. Mengirim password melalui HTTP memungkinkan penyadapan sebelum redirect.</p></>}<div className="notice">Operator perlu melengkapi identitas dan kanal dukungan layanan sebelum peluncuran publik.</div><Link className="button secondary" href={aup?'/terms':'/aup'}>{aup?'Terms of Service':'Acceptable Use Policy'} <ArrowUpRight size={15}/></Link></article>;}
export function Changelog(){return <article className="prose-page"><span className="page-eyebrow">A BETTER CONNECTION, ONE RELEASE AT A TIME</span><h1>What’s new.</h1><p className="lead">Perubahan implementasi dicatat terpisah dari hasil deployment.</p><div className="changelog-entry"><span className="pill">2.0.0 · Implementation</span><h2>A new foundation for audio.</h2><ul className="feature-list"><li>Next.js dashboard dan API dengan PostgreSQL.</li><li>Gateway dengan kredensial per client, pencabutan, dan kuota.</li><li>Dua node dengan TLS, monitoring persisten, dan riwayat insiden.</li><li>Bot contoh dan runner tes playback Discord bertahap.</li><li>Lavalink dipin ke 4.2.2 dan youtube-plugin 1.18.2.</li></ul><div className="notice">Rilis kode tidak berarti deployment atau pengujian audio produksi telah lulus. Lihat laporan verifikasi operator.</div></div></article>;}
