'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { Activity,ArrowUpRight,ArrowRight,AudioLines,Check,ChevronDown,Clock3,Copy,Database,Globe2,Headphones,Info,Play,Radio,RefreshCw,Server,ShieldCheck,Users,Zap } from 'lucide-react';
export type NodeData={id:string;name:string;provider:string;public_url:string|null;status:string;checked_at:string|null;players:number|null;playing:number|null;clients:number|null;cpu:number|null;ram_used:string|null;ram_allocated:string|null;latency_ms:number|null;uptime_pct:number|null;coverage_pct:number;daily_clients:number|null;playback:{checked_at:string;audible_confirmed:boolean}|null};
export type Metrics={generated_at:string;nodes:NodeData[];history:{node_id:string;time:string;players:string|null;latency_ms:string|null;samples:number;online_samples:number}[];incidents:{id:string;node_id:string;title:string;details:string;opened_at:string;resolved_at:string|null}[];requests:{node_id:string;minute:string;requests:number;errors:number;starts:number;exceptions:number;ends:number}[]};
const initialNodes:NodeData[]=['render','vps'].map((id,i)=>({id,name:i?'VPS · Node 02':'Render · Node 01',provider:i?'VPS':'Render',public_url:null,status:'UNKNOWN',checked_at:null,players:null,playing:null,clients:null,cpu:null,ram_used:null,ram_allocated:null,latency_ms:null,uptime_pct:null,coverage_pct:0,daily_clients:null,playback:null}));
export function useMetrics(){const[data,setData]=useState<Metrics|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 async function reload(){setLoading(true);try{const response=await fetch('/api/public',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('Monitoring belum tersedia. Periksa koneksi PostgreSQL dan worker.');setData(await response.json());setError('');}catch{setData(null);setError('Monitoring belum tersedia. Periksa koneksi PostgreSQL dan worker.');}finally{setLoading(false);}}
 useEffect(()=>{void reload();const timer=setInterval(()=>void reload(),30000);return()=>clearInterval(timer);},[]);return{data,error,loading,reload};}
export function CopyButton({value,label='Copy'}:{value:string;label?:string}){const[copied,setCopied]=useState(false);const[failed,setFailed]=useState(false);return <button className="copy-button" onClick={async()=>{try{await navigator.clipboard.writeText(value);setCopied(true);setFailed(false);setTimeout(()=>setCopied(false),2000);}catch{setFailed(true);}}}>{copied?<Check size={14}/>:<Copy size={14}/>} {failed?'Pilih & salin teks':copied?'Copied':label}</button>;}
function Metric({label,value,unit,Icon,note}:{label:string;value:number|null;unit?:string;Icon:typeof Activity;note:string}){return <div className="metric-card"><div className="metric-heading"><span>{label}</span><Icon size={17}/></div><div className="metric-value">{value===null?'—':value.toLocaleString('id-ID')}<span>{unit}</span></div><div className="metric-note"><span className={value===null?'muted-dot':'violet-dot'}/>{note}</div></div>;}
export function NodeCard({node}:{node:NodeData}){const state=node.status.toLowerCase();return <article className="node-card"><div className="node-card-top"><div className={`node-icon ${node.id}`}><Server size={21}/></div><span className={`status-badge ${state}`}><span/>{node.status==='UNKNOWN'?'Awaiting data':node.status.toLowerCase()}</span></div><div className="node-title"><h3>{node.name}</h3><span>{node.id==='render'?'01':'02'}</span></div><p className="node-subtitle">{node.provider} infrastructure <span>·</span> HTTPS / WSS</p><div className="node-endpoint"><Globe2 size={14}/><code>{node.public_url?new URL(node.public_url).hostname:'Endpoint belum dikonfigurasi'}</code>{node.public_url&&<CopyButton value={new URL(node.public_url).hostname} label=""/>}</div><div className="node-metrics"><div><small>ACTIVE PLAYERS</small><strong>{node.players??'—'}</strong></div><div><small>LATENCY</small><strong>{node.latency_ms??'—'}<em> ms</em></strong></div><div><small>SAMPLED UPTIME</small><strong>{node.uptime_pct??'—'}<em> %</em></strong></div></div><div className="connection-line"><span>Client connections <strong>{node.clients??'—'}</strong></span><span>Currently playing <strong>{node.playing??'—'}</strong></span></div><div className="node-footer"><span><ShieldCheck size={13}/>{node.playback?.audible_confirmed?'Audible test recorded':'Playback belum diverifikasi'}</span><Link href="/docs">Connect <ArrowUpRight size={14}/></Link></div></article>;}
function ActivityChart({data,metric='players'}:{data:Metrics|null;metric?:'players'|'latency_ms'}){const series=['render','vps'].map(id=>(data?.history??[]).filter(h=>h.node_id===id&&h[metric]!==null));const hasData=series.some(s=>s.length);const max=Math.max(1,...series.flat().map(s=>Number(s[metric])));const now=Date.now();return <div className="chart-area"><div className="chart-y"><span>{hasData?Math.ceil(max):'—'}</span><span>{hasData?Math.round(max/2):'—'}</span><span>0</span></div><div className="chart-plot"><div className="grid-lines"><i/><i/><i/><i/></div>{hasData?<svg viewBox="0 0 800 160" preserveAspectRatio="none" role="img" aria-label={metric==='players'?'Rata-rata player per jam':'Rata-rata latency per jam'}>{series.map((values,index)=>{const points=values.map(v=>`${Math.max(0,Math.min(800,(new Date(v.time).getTime()-(now-86400000))/86400000*800))},${150-Number(v[metric])/max*130}`).join(' ');return <g key={index}><polyline points={points} fill="none" stroke={index?'#5c9bff':'#9e7aff'} strokeWidth="2.5" vectorEffect="non-scaling-stroke"/>{values.length===1&&<circle cx={points.split(',')[0]} cy={points.split(',')[1]} r="3" fill={index?'#5c9bff':'#9e7aff'}/>}</g>;})}</svg>:<div className="chart-empty"><Activity size={22}/><strong>Waiting for the first signal</strong><span>Grafik akan muncul setelah worker mengumpulkan data nyata.</span></div>}<div className="chart-x"><span>24h ago</span><span>18h ago</span><span>12h ago</span><span>6h ago</span><span>Now</span></div></div></div>;}
export function Overview({mode='overview'}:{mode?:string}){const{data,error,loading,reload}=useMetrics();const nodes=data?.nodes??initialNodes;const[chartMetric,setChartMetric]=useState<'players'|'latency_ms'>('players');
 const total=(key:'players'|'playing'|'clients'|'daily_clients')=>nodes.every(n=>n[key]!==null)?nodes.reduce((s,n)=>s+(n[key]??0),0):null;
 const requests=data?.requests.reduce((s,r)=>s+r.requests,0)??0, errors=data?.requests.reduce((s,r)=>s+r.errors,0)??0;
 return <div className="page-enter"><div className="page-eyebrow"><span className="eyebrow-line"/> THE AUDIO INFRASTRUCTURE FOR DISCORD</div><div className="page-heading"><div><h1>{mode==='nodes'?'A home for every beat.':mode==='statistics'?'Every connection, accounted for.':mode==='uptime'?'Clarity at every moment.':<>Your sound. <span>Always connected.</span></>}</h1><p>{mode==='uptime'?'Status transparan, riwayat insiden, dan cakupan monitoring.':'Dua node. Satu ruang kendali. Infrastruktur audio untuk bot Discord kamu.'}</p></div><Link href="/docs" className="button"><TerminalIcon/> Connect your bot <ArrowUpRight size={16}/></Link></div>
 {mode==='overview'&&<div className="intro-banner"><div className="banner-glow"/><div className="intro-copy"><span className="pill"><span/> LAVALINK V4 · TWO-NODE NETWORK</span><h2>Less setup.<br/>More <span>music.</span></h2><p>Dari koneksi pertama hingga track berikutnya.<br/>Kendalikan audio dengan akses aman dan monitoring terbuka.</p><Link href="/bot">Build your first connection <ArrowRight size={16}/></Link></div><div className="sound-visual" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><div className="waveform">{Array.from({length:45},(_,i)=><i key={i} style={{height:18+Math.pow(Math.sin(i*.68),2)*(95-Math.abs(i-22)*3)+'px',animationDelay:`${i*0.08}s`}}/>)}</div><div className="wave-label"><AudioLines size={13}/> ENGINEERED FOR YOUR NEXT TRACK</div></div></div>}
 <div className="section-title"><h2>{mode==='uptime'?'Network health':'Network overview'} <span className="tiny-tag">LIVE TELEMETRY</span></h2><button className="text-button" onClick={()=>void reload()} disabled={loading}><RefreshCw size={13} className={loading?'spin':''}/>{loading?'Refreshing':'Refresh'}<span className="subtle">· every 30s</span></button></div>
 {error&&<div className="notice" role="alert"><Info size={16}/>{error}</div>}
 <div className={`metrics-grid ${loading&&!data?'loading-metrics':''}`}><Metric label="Active players" value={total('players')} Icon={Headphones} note="Player yang dialokasikan"/><Metric label="Currently playing" value={total('playing')} Icon={Play} note="Player yang sedang memutar"/><Metric label="Connected clients" value={total('clients')} Icon={Users} note="Koneksi aktif ke gateway"/><Metric label="Daily active clients" value={total('daily_clients')} Icon={Radio} note="Kredensial unik per node · UTC"/></div>
 {mode!=='uptime'&&<div className="chart-row"><section className="panel activity-panel"><div className="panel-heading"><div><h3>Network activity</h3><p>Pengamatan aktual selama 24 jam terakhir</p></div><div className="chart-controls"><select aria-label="Metrik grafik" value={chartMetric} onChange={e=>setChartMetric(e.target.value as 'players'|'latency_ms')}><option value="players">Active players</option><option value="latency_ms">Latency</option></select><span className="period">24 hours <ChevronDown size={12}/></span></div></div><ActivityChart data={data} metric={chartMetric}/><div className="chart-legend"><span><i className="violet-dot"/>Render Node 01</span><span><i className="blue-dot"/>VPS Node 02</span><small>Hourly averages · UTC</small></div></section><section className="panel readiness-panel"><div className="mini-icon"><Zap size={20}/></div><h3>Know what’s playing.</h3><p>Koneksi sehat adalah langkah pertama. Audio yang terdengar adalah tujuan akhirnya.</p><div className="readiness-step"><span>01</span><div>Connect & resolve<small>REST + WebSocket</small></div><span className="readiness-label">Measured</span></div><div className="readiness-step"><span>02</span><div>Verify voice playback<small>Discord voice + UDP</small></div><Link href="/bot"><ArrowUpRight size={16}/></Link></div><Link href="/bot" className="readiness-link">View playback checklist <ArrowRight size={14}/></Link></section></div>}
 <div className="section-title"><h2>Audio nodes <span className="count-badge">2</span></h2><Link className="text-button" href={mode==='nodes'?'/uptime':'/nodes'}>{mode==='nodes'?'View status history':'View all nodes'} <ArrowUpRight size={14}/></Link></div><div className="node-grid">{nodes.map(node=><NodeCard key={node.id} node={node}/>)}</div>
 {mode==='statistics'&&<><div className="section-title"><h2>Resource & request telemetry</h2><span className="subtle">24 hour window</span></div><div className="metrics-grid"><Metric label="Protocol requests" value={data?.requests.length?requests:null} Icon={Activity} note="REST terautentikasi di gateway"/><Metric label="Request error rate" value={requests?Math.round(errors/requests*10000)/100:null} unit="%" Icon={Info} note="HTTP ≥400 atau loadType error"/><Metric label="Track starts" value={data?.requests.length?data.requests.reduce((s,r)=>s+r.starts,0):null} Icon={Play} note="TrackStartEvent yang teramati"/><Metric label="Playback exceptions" value={data?.requests.length?data.requests.reduce((s,r)=>s+r.exceptions,0):null} Icon={Radio} note="TrackExceptionEvent"/></div><div className="panel table-panel"><table><thead><tr><th>Node</th><th>CPU Lavalink</th><th>RAM used / allocated</th><th>Sample coverage / 24h</th></tr></thead><tbody>{nodes.map(n=><tr key={n.id}><td>{n.name}</td><td>{n.cpu===null?'—':`${(n.cpu*100).toFixed(1)}%`}</td><td>{n.ram_used===null?'—':`${Math.round(Number(n.ram_used)/1048576)} / ${Math.round(Number(n.ram_allocated)/1048576)} MiB`}</td><td>{n.coverage_pct}%</td></tr>)}</tbody></table></div><section className="panel table-panel"><div className="panel-heading"><h3>Request history</h3><span className="tiny-tag">LATEST 20 MINUTE BUCKETS · UTC</span></div>{data?.requests.length?<table><thead><tr><th>Time (UTC)</th><th>Node</th><th>Requests</th><th>Errors</th><th>Track starts</th><th>Track ends</th></tr></thead><tbody>{[...data.requests].reverse().slice(0,20).map(r=><tr key={r.node_id+r.minute}><td>{new Date(r.minute).toISOString().slice(0,16).replace('T',' ')}</td><td>{r.node_id}</td><td>{r.requests}</td><td>{r.errors}</td><td>{r.starts}</td><td>{r.ends}</td></tr>)}</tbody></table>:<div className="empty-inline"><Activity size={20}/><p>Belum ada request terautentikasi yang tercatat.</p></div>}</section><p className="muted-copy">Daily active clients adalah kredensial unik per node, bukan pengguna Discord atau bot unik. Satu operator dapat memiliki beberapa kredensial. Statistik website tidak digabungkan dengan statistik audio.</p></>}
 <div className="bottom-grid"><section className="panel incident-panel"><div className="panel-heading"><h3>Recent incidents</h3><Link href="/uptime" className="text-button">Status history <ArrowUpRight size={14}/></Link></div>{data?.incidents.length?data.incidents.slice(0,mode==='uptime'?30:3).map(i=><div className="incident" key={i.id}><span className={`incident-dot ${i.resolved_at?'resolved':''}`}/><div><strong>{i.title}</strong><p>{i.details}</p><small>{new Date(i.opened_at).toLocaleString('id-ID')} · {i.resolved_at?'Resolved':'Investigating'}</small></div></div>):<div className="empty-inline"><Clock3 size={24}/><div><strong>{data?'No recorded incidents':'History is waiting for data'}</strong><p>{data?'Belum ada insiden tersimpan. Ini bukan jaminan uptime.':'Riwayat tersedia setelah database dan worker terhubung.'}</p></div></div>}{mode==='uptime'&&<p className="muted-copy">Uptime = sampel ONLINE / seluruh sampel dalam 24 jam. Coverage ditampilkan terpisah; interval hilang bukan waktu online. Probe kontrol tidak membuktikan playback.</p>}</section><section className="quickstart-card"><BookIcon/><h3>A few lines. A new soundtrack.</h3><p>Panduan koneksi, kontrol player, dan pengujian audio Discord.</p><Link href="/docs">Explore the docs <ArrowRight size={15}/></Link></section></div>
 <div className="data-footnote"><Database size={12}/>{data?`Last fetched ${new Date(data.generated_at).toLocaleTimeString('id-ID')} · PostgreSQL · stale samples become UNKNOWN after 90s`:'Tidak ada angka simulasi. Metrik kosong berarti belum terukur.'}<Link href="/docs#metrics">How we measure <ArrowUpRight size={12}/></Link></div></div>;
}
function TerminalIcon(){return <span className="terminal-symbol">⌘</span>;}function BookIcon(){return <div className="mini-icon"><AudioLines size={21}/></div>;}
