'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { AudioLines, LayoutDashboard, Server, ChartNoAxesCombined, Activity, BookOpen, Terminal, History, ArrowUpRight, ChevronRight, Menu, X, ShieldCheck, Headphones } from 'lucide-react';
const groups=[{title:'WORKSPACE',items:[['/','Overview',LayoutDashboard],['/nodes','Audio nodes',Server],['/statistics','Usage analytics',ChartNoAxesCombined],['/uptime','Uptime & incidents',Activity]]},{title:'RESOURCES',items:[['/docs','Documentation',BookOpen],['/bot','Bot integration',Terminal],['/changelog','Changelog',History]]}] as const;
export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname();const[open,setOpen]=useState(false);
 const title=groups.flatMap(g=>[...g.items]).find(i=>i[0]===path)?.[1]??(path==='/account'?'Your workspace':path==='/admin'?'Administration':'Resonance');
 return <><aside className={`sidebar ${open?'open':''}`}><Link href="/" className="brand" onClick={()=>setOpen(false)}><span className="brand-icon"><AudioLines size={23}/></span>resonance<span className="brand-dot">.</span></Link><button className="mobile-close icon-button" onClick={()=>setOpen(false)} aria-label="Tutup menu"><X/></button><div className="workspace-selector"><span className="workspace-avatar">R</span><div>Public workspace<small>Audio infrastructure</small></div><span className="tiny-tag">v4</span></div><nav>{groups.map(group=><div className="nav-group" key={group.title}><p>{group.title}</p>{group.items.map(([href,label,Icon])=><Link key={href} className={`nav-link ${path===href?'active':''}`} href={href} onClick={()=>setOpen(false)}><Icon size={18}/>{label}{path===href&&<span className="active-dot"/>}</Link>)}</div>)}</nav><div className="sidebar-bottom"><div className="sidebar-help"><Headphones size={22}/><h4>Built for your next beat.</h4><p>Hubungkan bot, pilih node,<br/>dan mulai sesi audio.</p><Link href="/docs">Get started <ArrowUpRight size={15}/></Link></div><Link href="/account" className="profile-link"><span className="profile-avatar">U</span><div>Your workspace<small>Manage your access</small></div><ChevronRight size={16}/></Link></div></aside>{open&&<button className="overlay" onClick={()=>setOpen(false)} aria-label="Tutup navigasi"/>}<div className="app-main"><header className="topbar"><div className="breadcrumbs"><button className="mobile-menu icon-button" onClick={()=>setOpen(true)} aria-label="Buka menu"><Menu size={20}/></button><span>Workspace</span><ChevronRight size={13}/><strong>{title}</strong></div><div className="topbar-actions"><Link className="release-tag" href="/changelog"><span/> Lavalink v4.2.2</Link><span className="topbar-divider"/><Link href="/login" className="login-link">Log in</Link><Link href="/register" className="button small">Get access <ArrowUpRight size={14}/></Link></div></header><main>{children}</main><footer><span>© {new Date().getFullYear()} Resonance <span className="footer-separator">/</span> Made for the music.</span><div><Link href="/terms">Terms of Service</Link><Link href="/aup">Acceptable Use</Link><span><ShieldCheck size={13}/> TLS required</span></div></footer></div></>;
}
